### ISSUE TITLE
image signing for compatibility with ublue-os/startingpoint

### ISSUE THREAD

**Issue by qoijjj** [ublue-os/ucore#101]
If an image ingestion is attempted in startingpoint, for either ucore or for coreos from this project, the following errors appear:

cp: cannot create regular file '/usr/etc/pki/containers/ucore.pub': No such file or directory

**Comment by qoijjj** [comment]
Over at secureblue we have server versions but because of this we have to use ublue-os/base instead of ucore or coreos from this project. We're prefer to use this project instead.

https://github.com/secureblue/secureblue/issues/58

**Comment by bsherman** [comment]
with #109 built, I've tested the following:

```
$ sudo rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/ucore:stable-nvidia-zfs
Pulling manifest: ostree-image-signed:docker://ghcr.io/ublue-os/ucore:stable-nvidia-zfs
Staging deployment... done
Freed: 227.8 kB (pkgcache branches: 0)
Changes queued for next boot. Run "systemctl reboot" to start a reboot
```

I think that's what you were asking for right?

Let me know if this is good to close.
