### ISSUE TITLE
ublue-nvctk-cdi.service does not start by default

### ISSUE THREAD

**Issue by bsherman** [ublue-os/ucore#102]
On nvidia versions of the ucore image, the ublue-nvctk-cdi.service should start automatically to ensure containers are able to use nvidia drivers.

On a fresh rebase from CoreOS to ucore:nvidia this is what happens:

```
# systemctl status ublue-nvctk-cdi.service
○ ublue-nvctk-cdi.service - ublue nvidia container toolkit CDI auto-generation
     Loaded: loaded (/usr/lib/systemd/system/ublue-nvctk-cdi.service; disabled; preset: enabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: inactive (dead)
```

**Comment by bsherman** [comment]
I suspect presets are only applied on first boot, otherwise useful as a way to know what the package maintainer intended as default, and possibly as a way to reset to defaults with some tool I have yet to investigate.

Also, note that this is the `ucore` repo not ublue `nvidia`... We had the same issue there when we implemented and added this: https://github.com/ublue-os/nvidia/blob/main/post-install.sh#L7

**Comment by EyeCantCU** [comment]
I think this makes a strong case for shipping a hardware setup script that handles stuff like this under NVIDIA images to ensure things are always configured correctly

**Comment by bsherman** [comment]
> I think this makes a strong case for shipping a hardware setup script that handles stuff like this under NVIDIA images to ensure things are always configured correctly

Can you elaborate on what you mean?

A couple preemptive comments :-)  ...
1. ucore uses a different version of the `ublue-os-nvidia-addons` RPM though it could probably be made sharable if we wanted.
2. the nvidia-addons RPM (both in ucore and ublue) ships this service `ublue-nvctk-cdi` which automatically configures any present nvidia GPUs for use in containers.
3. other than this service, I don't think we've ever needed any setup for nvidia cards (not counting kargs/secureboot) save for the container configs which were used by older nvidia container runtime.

**Comment by EyeCantCU** [comment]
> > I think this makes a strong case for shipping a hardware setup script that handles stuff like this under NVIDIA images to ensure things are always configured correctly
> 
> Can you elaborate on what you mean?
> 
> A couple preemptive comments :-)  ...
> 1. ucore uses a different version of the `ublue-os-nvidia-addons` RPM though it could probably be made sharable if we wanted.
> 2. the nvidia-addons RPM (both in ucore and ublue) ships this service `ublue-nvctk-cdi` which automatically configures any present nvidia GPUs for use in containers.
> 3. other than this service, I don't think we've ever needed any setup for nvidia cards (not counting kargs/secureboot) save for the container configs which were used by older nvidia container runtime.
> 

Definitely, though in hindsight and after reading this comment here I'm unsure it would be fit for Ucore

In Bazzite, we ship a hardware setup script that enables initramfs, configures it to handle the NVIDIA driver, and manages all other NVIDIA specific configuration, factoring in whether or not the system has been rebased or the script updated. It would be useful in main NVIDIA images but given that isn't really done here, you're right. It's not applicable in that sense

I guess its application here would simply be to check if the service is disabled and enable it if not. I'm unsure if changing the service's state here will have an overreaching impact if somehow it was disabled elsewhere. That does however seem excessive
