### ISSUE TITLE
Include sanoid in zfs images

### ISSUE THREAD

**Issue by johnmmcgee** [ublue-os/ucore#130]
sanoid is mentioned in the documentation.   It is an excellent tool to automate zfs snapshot management, amongst other things.   This should be added as a "Batteries Included" feature. 

https://github.com/jimsalterjrs/sanoid

There is already a spec file, as well: https://github.com/jimsalterjrs/sanoid/blob/master/packages/rhel/sanoid.spec

**Comment by bsherman** [comment]
I think we agree, we wouldn't add this to the "just fcos + zfs" images, but... 

Do you think we should add to all the ucore zfs images? Or not `ucore-minimal:zfs`? I'm not sure, though, if you want ZFS, tis super userful and your minimal already is not TOO minimal :-)

But I 100% agree without questions for `ucore:zfs` and `ucore-hci:zfs`.

**Comment by bsherman** [comment]
> I second `ucore:zfs` and `ucore-hci:zfs`. This should not be in `ucore-minimal:zfs`.

Fine with me.

I did just check and our current `ucore-minimal:zfs` DOES include the perl deps required by sanoid, so we'll need to remove them, but i think that's fine, since probably, the RPM will pull them as a dependency wherever we add it.

Adding here for permanent memory. :-)

**Comment by johnmmcgee** [comment]
https://github.com/ublue-os/packages/pull/16

**Comment by bsherman** [comment]
I've merged this.
