### ISSUE TITLE
mergerfs not installed in ucore/ucore-hci

### ISSUE THREAD

**Issue by bsherman** [ublue-os/ucore#157]
Discord report of this package not getting installed as intended: https://discord.com/channels/1072614816579063828/1083811821846286428/1222707559459455006

> https://github.com/ublue-os/ucore/blob/a27bd758e05ad42810e86a1b11273d9ea4d34b88/ucore/install-ucore.sh#L15
>
> it needs to be fc<version>.x86_64

**Comment by bsherman** [comment]
I think this was related to the `mergerfs` package changing it's naming format.

**Comment by mixedd69** [comment]
On `ucore:stable` it's also absent
