### ISSUE TITLE
[feat] add a set of images that include ublue-os/config

### ISSUE THREAD

**Issue by qoijjj** [ublue-os/ucore#168]
ujust would be really nice to have on ucore ootb

**Comment by bsherman** [comment]
I'm not 100% against the idea, but I do think several of the ujust recipes we have for desktop don't make sense on ucore.  

For that reason, I'm hesitant to simply install the ujust package. At the very list I'd want to review them first.

**Comment by qoijjj** [comment]
@bsherman In secureblue we use patchfiles to cleanly remove irrelevant upstream justfiles. I can do the same for ucore if that makes sense to you

**Comment by bsherman** [comment]
Added comments and a request to close here: https://github.com/ublue-os/ucore/pull/187#issuecomment-2308662362

**Comment by qoijjj** [comment]
https://github.com/ublue-os/ucore/pull/187#issuecomment-2308662362
