### ISSUE TITLE
Podman containers do not start on reboot, even with `restart: always`

### ISSUE THREAD

**Issue by alangrainger** [ublue-os/ucore#188]
## Steps to reproduce

1. Make a clean install of UCore. I'm using `ostree-image-signed:docker://ghcr.io/ublue-os/ucore:stable`, version `40.20240728.3.0 (2024-08-20T23:44:05Z)`
2. Create a `docker-compose.yml` file.
3. Add in:

```yaml
services:
  web:
    image: nginx
    restart: always
```

4. Start the container with `podman-compose up -d`
5. Verify the container is running with `podman ps`.
6. Reboot the machine.
7. The container will not automatically start after reboot.

---

### Workaround / possible solution

I think I have figured out the issue.

There is a `podman-restart.service` which runs:

```bash
/usr/bin/podman start --all --filter restart-policy=always
```

This service is set to run as root. If I manually run that command as the root user (sudo), none of the containers will start.

If I run that command as the `core` user, the containers come up correctly. So I think this systemctl service should be in the user space not in the root space, and that will solve the problem.

To fix this, you can run:

```bash
# Copy the system's podman-restart service to the user location
cp /lib/systemd/system/podman-restart.service /var/home/core/.config/systemd/user

# Enable the user service
systemctl --user enable podman-restart.service

# Check that it's running
systemctl --user list-unit-files | grep podman
```

Then reboot, and your containers will automatically start.

It's possible you also need to enable "linger" mode on your user session, to prevent containers exiting which you've started interactively. I got this from the Podman [troubleshooting page](https://github.com/containers/podman/blob/main/troubleshooting.md#21-a-rootless-container-running-in-detached-mode-is-closed-at-logout):

```bash
loginctl enable-linger $UID
```

I can confirm this mode is not enabled by default on UCore.

**Comment by bsherman** [comment]
I agree with your assessment of the default state of things. There's no bug here (I recognize our bot added the bug label, not you @alangrainger )

To quote our README:
> most add-on services are not auto-enabled.

I'm not included to pre-enable the `podman` and `podman-restart` system services, but even if we did, I don't think that would address the per-user, rootless situation without further effort.

I would welcome a some contribution to the "Tips and Tricks" section of the README regarding this topic.

Thanks!
