### ISSUE TITLE
libgcc toolchain mismatch

### ISSUE THREAD

**Issue by m2Giles** [ublue-os/ucore#189]
The gcc toolchain has a mismatch of versions installed. libgomp has a prerelease version installed while all other portions of the toolchain are the latest release.

This prevents gcc and other parts of the toolchain from getting installed.

**Comment by bsherman** [comment]
```
rpm -q libgcc
libgcc-14.1.1-7.fc40.x86_64
```

`libgcc` seems to come from here: https://github.com/coreos/fedora-coreos-config/blob/stable/manifest-lock.x86_64.json#L1287-L1291

```
    "libgcc": {
      "evra": "14.1.1-7.fc40.x86_64",
      "metadata": {
        "sourcerpm": "gcc"
      }
```

This is a fixed version, older than what is current in Fedora... `libgomp` is actually current.

This is exactly the kind of problem I previously attempted to fix by using the [fedora-coreos-pool repo](https://github.com/coreos/fedora-coreos-config/blob/stable/fedora-coreos-pool.repo) which sources direct from koji back in #167 


I don't think we recommend users install gcc direct on a CoreOS install, as that should be done in distrobox, etc...

@m2Giles are you trying to install gcc at build time or something? we could temporarily add the fedora-coreos-pool repo, but if it's left in place globally, pre-release (even fc41) packages are improperly installed, thus #178 to remove that repo.

**Comment by m2Giles** [comment]
I was trying to install gcc as part of using brew. But the actual issue that identified it was Antheas rechunk needs them to have same package version.

**Comment by bsherman** [comment]
> I was trying to install gcc as part of using brew. But the actual issue that identified it was Antheas rechunk needs them to have same package version.

For context, [rechunk](https://github.com/hhd-dev/rechunk) ...

@m2Giles maybe you have a build log I can review? I'm not 100% sure what you are telling me. I think it's a generic problem with the way coreos pins its rpm versions and doesn't provide a yum repo which provides the pinned version, but, with rechunker in the mix, I'm confused.

I don't see how we're ever going to have the "same version" in a coreos based image for gcc, given the coreos pinning strategy.

**Comment by antheas** [comment]
> I was trying to install gcc as part of using brew. But the actual issue that identified it was Antheas rechunk needs them to have same package version.

I think you are referring to this fix:
https://github.com/hhd-dev/rechunk/releases/tag/v0.8.4

It was caused by an uncaught logic error due to the image being too small...

**Comment by bsherman** [comment]
I believe we determined this to be related to rechunker and not an actual flaw in uCore.

Good for me to close @m2Giles ?

**Comment by m2Giles** [comment]
Good to close. The issue was with held back libgcc but has since been resolved.
