### ISSUE TITLE
feat: Add cockpit-ostree to ucore-minimal for UI-based updates

### ISSUE THREAD

**Issue by skyfenton** [ublue-os/ucore#196]
Not that it's a big deal, but it'd be nice to have software updates and rebase options shown through [cockpit-ostree](https://github.com/cockpit-project/cockpit-ostree).

**Comment by bsherman** [comment]
I've been running systems with cockpit-ostree added as a test, and I'm not sure it's the best idea to add this.

My reasons:
1) currently, we use container native ostree for ucore. And it seems cockpit-ostree isn't aware of container native targets. 

This results is some odd behavior... rebasing isn't actually an option for example.

![Image](https://github.com/user-attachments/assets/6976ef97-03db-4a7f-ba1a-d9edb3d4e82f)

That said, you CAN use this UI to update and rollback. But the experience is a bit confusing.

2) soon, Fedora CoreOS will be fully switched over to bootc and composefs (already there in coreos:testing).  I've not yet tested this feature on that release, but as ostree moves more into the background and bootc to the forefront, I have a feeling `cockpit-ostree` will be even more incongruent with the CoreOS and thus uCore.

I'd guess we'll be looking for `cockpit-bootc` to show up.

**Comment by bsherman** [comment]
Closing after some discussion with other folks in our discord. We agree that with bootc coming and ostree diminishing this isn't the best fit.

Can revisit if this package converts to have bootc support etc.
