### ISSUE TITLE
No ZFS in ucore:stable-zfs?

### ISSUE THREAD

**Issue by thomasazar** [ublue-os/ucore#210]
This morning, I saw a number of errors on my home network, apparently due to missing mounts. After logging into my server and running `zfs list`, I saw a rather dreadful message:

``
The ZFS modules cannot be auto-loaded.
Try running 'modprobe zfs' as root to manually load them.
``

So I dutifully ran the `modprobe` command, and I was met with this:

``
modprobe: FATAL: Module zfs not found in directory /lib/modules/6.11.3-300.fc41.x86_64)
``

Confident in the atomic nature of the server, I quickly entered `rpm-ostree rollback`, then rebooted into having a working zpool again. It looks like the rebase onto Fedora 41 may not have built the ZFS modules? (I'll confess, I don't know much about the underpinnings of ucore.) The rollback is still based on Fedora 40, so I'm pinning it for now.

**Comment by thomasazar** [comment]
Here's the output from `rpm-ostree status`:

```
State: idle
AutomaticUpdates: apply; rpm-ostreed-automatic.timer: last run 1h 29min ago
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/ucore:stable-zfs
                   Digest: sha256:5e139150cef36fb937e8b9a905c50d3f0e10fbec1061748cefb71b0125c0a7b8
                  Version: 41.20241027.3.0 (2024-11-13T03:02:55Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/ucore:stable-zfs
                   Digest: sha256:1bae328358cda9c089b03cb0150318ae8c0492c3ba6d279e42b385f9d432e3f9
                  Version: 40.20241019.3.0 (2024-11-12T03:01:59Z)
```

The top image is where the error occurred, the bottom one is the one to which I rolled back.

**Comment by bketelsen** [comment]
I'm getting this too!

**Comment by bsherman** [comment]
I'm investigating this issue...

So far I'm quite confused as I can reproduce on a test VM but not on my main home server with a lot of ZFS ... even on the latest update, that machine is still working fine.

**Comment by bsherman** [comment]
As @m2Giles this seems like a depmod issue... as the ZFS kmod files are certainly present and can be loaded.

```
root@test-ucore-stable:~# rpm-ostree status -b
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
BootedDeployment:
● ostree-unverified-image:docker://ghcr.io/ublue-os/ucore:stable-zfs-20241112
                   Digest: sha256:b58d52d627448614ee5d6a5dc67827c8328d446966f19c97e9abb88c1ab822d3
                  Version: 41.20241027.3.0 (2024-11-12T20:30:20Z)
root@test-ucore-stable:~# modprobe zfs
modprobe: FATAL: Module zfs not found in directory /lib/modules/6.11.3-300.fc41.x86_64
root@test-ucore-stable:~# insmod /lib/modules/6.11.3-300.fc41.x86_64/extra/zfs/spl.ko 
root@test-ucore-stable:~# insmod /lib/modules/6.11.3-300.fc41.x86_64/extra/zfs/zfs.ko 
root@test-ucore-stable:~# 
```

**Comment by bsherman** [comment]
@thomasazar and @bketelsen  I believe the stable build after mergint #211 has resolved the issue for me in my test VM.

Can you confirm and we'll close this as fixed?

**Comment by bsherman** [comment]
@bketelsen confirmed this fixed the issue for him via Discord thread.

**Comment by thomasazar** [comment]
Indeed, everything is coming up ZFS on my updated server. Thank you!
