### ISSUE TITLE
mergerfs missing since update to Fedora 41

### ISSUE THREAD

**Issue by bsherman** [ublue-os/ucore#214]
Reported by Zephyr in Discord, `mergerfs` is missing since uCore's update to Fedora 41.

Turns out this is because the upstream package hasn't had a release build since February and Fedora 41 wasn't a thing then, so there is no package to install.

There are a few problems here:
1. upstream not providing a package... we can't fix that but I filed a request for a package to be published: https://github.com/trapexit/mergerfs/issues/1370
2. our uCore workflow should fail if trying to install an RPM from github and not finding one to install. Then we won't be surprised by missing packages.

Workaround:
Static binary packages are available in the latest [mergerfs release](https://github.com/trapexit/mergerfs/releases/tag/2.40.2).  It is certainly possible to manually download this and extract to `/usr/local`.

And perhaps uCore will switch to this simply to get the functionality back ASAP.

**Comment by Reuh** [comment]
Thank you for the quick fix, but unfortunately using `mergerfs` as a filesystem type in /etc/fstab now fails with `unknown filesystem type 'mergerfs'` since there doesn't seem to be a `/sbin/mount.mergerfs` executable in the static binary tarball, unlike the package.

I have replaced `mergerfs` with `fuse.mergerfs` in my fstab as a workaround.

**Comment by bsherman** [comment]
> Thank you for the quick fix, but unfortunately using `mergerfs` as a filesystem type in /etc/fstab now fails with `unknown filesystem type 'mergerfs'` since there doesn't seem to be a `/sbin/mount.mergerfs` executable in the static binary tarball, unlike the package.
> 
> I have replaced `mergerfs` with `fuse.mergerfs` in my fstab as a workaround.

@Reuh thanks for reporting that issue.

Thankfully upstream has responded to our bug report about missing Fedora 41 package and provided the build. 

See the change and add any comments in #220
