### ISSUE TITLE
breakout ZFS into distinct image tags

### ISSUE THREAD

**Issue by bsherman** [ublue-os/ucore#46]
I'm starting to be convinced ZFS should not be in the `ucore` man image...

It only adds about 200MB to the image, but by it is definitely only a requirement for some users.

My thoughts on this:
- build `ucore-kmods` images where ZFS RPMs can be sourced
- build `fedora-coreos-zfs` - stock CoreOS with only ZFS added
- build `ucore` without zfs, keeping `:stable` and `:testing` tags
- add new build job after build-ucore which adds `zfs` to stable and testing resulting in these tags for `ucore`
    - `:stable` - no zfs
    - `:stable-zfs` - stable CoreOS with ZFS 
    - `:testing` - no zfs
    - `:testing-zfs` - testing CoreOS with ZFS

`ucore-hci` will be built by adding its packages to all the `ucore` permutations, so it will have similar tagging.

--------------------------------
Edit August 9, 2023:  
- added `ucore-kmods`
- added `fedora-coreos-zfs`
- dropped adding "ZFS previous version" to simplify tags

**Comment by castrojo** [comment]
From an ops perspective it would be nice to have vanilla CoreOS with no modifications other than ZFS as a so it's a not overly opinionated base image with what people really want, which they can't get from stock CoreOS. 😄 

Probably a seperate issue: Someday when there's a Stream/Alma ostree build it'd be nice to have a build for that as well since that'd be an interesting combo.

**Comment by bsherman** [comment]
> it would be nice to have vanilla CoreOS with no modifications other than ZFS

thanks for complicating my life. ;-)

Actually, this does have me thinking about how to improve the build process.

Could create an `fcos-akmods` repo (like ublue's `akmods`):
there is where zfs gets built...

then we could easily have a simple `fcos-zfs` image build...

and keep `ucore` mostly as is, except use the `fcos-akmods` zfs in it's zfs variant.

**Comment by bsherman** [comment]
This ticket is in progress...

Step ONE was to break out kmods into a distinct repo: https://github.com/ublue-os/ucore-kmods

ZFS is now being built in that repo and installed to `ucore` from that image.
