### ISSUE TITLE
Add the qemu-guest-agent package to the setup

### ISSUE THREAD

**Issue by Nitrousoxide** [ublue-os/ucore#49]
CoreOS, being primarily designed for vms or for being deployed in the cloud will usually not be the bare metal install on a system, though it can be.  As such since QEMU is usually the vm framework that is used to deploy it having qemu-guest-agent installed is helpful to allow the host VM service to report ip and utilization metrics up the chain.

I realize that CoreOS leans heavily into keeping things as slim as possible, but this seems like a package that should be useful for nearly every virtualized install.

**Comment by bsherman** [comment]
I'm wondering about adding also virtualbox-guest-extensions and open-vm-tools, though, as I type this, I realize I feel sorry for anyone trying to do more than TEST ucore/coreos on a virtualbox desktop host, so I don't want to encourage that.  but maybe open-vm-tools does belong as VMware ESXi is a reasonable way to run a bunch VMs.
