### ISSUE TITLE
Add nvidia kernel module signing to enable SecureBoot mode

### ISSUE THREAD

**Issue by bsherman** [ublue-os/ucore#82]
It should be reasonable to add signing for the nvidia kmod since we use an akmod build the same as is done over in https://github.com/ublue-os/akmods 

The same signing key can even be used, though we'll also want to add that pub key here and instructions how to use it.

**Comment by m2Giles** [comment]
Please enable secureboot. Without secureboot, automatic luks decryption using tpm2 (via systemd-cryptenroll) is pointless.

**Comment by bsherman** [comment]
It turns out that we have been signing the nvidia kmod for some time, but not providing the pub key in the image.

This ticket will remedy that and should add some documentation for how to import.
