### ISSUE TITLE
File Sharing/NAS Use Case

### ISSUE THREAD

**Issue by bsherman** [ublue-os/ucore#87]
We've suggested that ucore can be used for a NAS... So, what's that mean? What would we install?

**NFS**: this is relatively simple to make work for CoreOS:
1. install `nfs-utils` and override/exclude `nfs-utils-coreos`
2. enable/start `nfs-server` service
3. enable firewall rules
```
firewall-cmd --permanent --zone=FedoraServer --add-service=nfs
firewall-cmd --permanent --zone=FedoraServer --add-service=nfs3
firewall-cmd --reload
```
4. this doesn't create shares, but this is what's required to be ready for that... it could be used by `zfs set sharenfs=on tank/foo` or adding entries to `/etc/exports`

**Samba**: not much more difficult, but a bit:
1. install `samba` and `samba-usershares` (`samba-client` maybe useful for debugging)
2. enable/start `smb` service
3. enable firewall rules
```
firewall-cmd --permanent --zone=FedoraServer --add-service=samba
firewall-cmd --reload
```
4. if running SELinux need to `setsebool -P samba_export_all_rw 1` or else `semanage fcontext --add --type "samba_share_t" "/path/to/share(/.*)?"` for any path which will be shared
5. this also doesn't create shares, but is what's needed to be ready for that... can be used by `zfs set sharesmb=on tank/foo` or running `net usershare add sharename abspath [comment] [user:{R|D|F}] [guest_ok={y|n}]` or manually adding entries to `/etc/samba/smb.conf`

I did install and play with `cockpit-file-sharing` and it works... however, it forcibly requires the `cockpit-ws` package which does NOT work on CoreOS, and we instead run via container, when needed.

Overall thoughts... We could install the required packages (in `ucore` image?)  but not enable the services or modify the firewall, but add the above required steps for enabling/using as examples in the README or `examples/` directory.

**Comment by bsherman** [comment]
Also should have links to docs:
- https://docs.fedoraproject.org/en-US/quick-docs/samba/
-

**Comment by bsherman** [comment]
Consider using https://github.com/samba-in-kubernetes/samba-container instead of host mode Samba.

**Comment by johnmmcgee** [comment]
> Consider using https://github.com/samba-in-kubernetes/samba-container instead of host mode Samba.

I have done some testing with this image.  I have currently hit a limitation due to the need for user shares in my current configuration.

Samba expects either users in /etc/passwd, or I believe accessible from sssd/ldap.
Bind mounting /etc/passwd from the host os isn't something we should consider (and it doesn't work.. I have tried)
The container linked does have a method for creating local users, however it doesn't appear to be very secure. 

I am doing further testing.

So far, installing from rpm-ostree, as a layered package, appears to be the best method.
