### ISSUE TITLE
zfs 2.2.0 : modprobe FATAL module zfs not found

### ISSUE THREAD

**Issue by bsherman** [ublue-os/ucore#88]
2 days ago, ZFS version 2.2.0 dropped, and as usual, we auto-built the latest version.

I just realized while the builds are all clean, systems upgraded to this version are not able to cleanly load the zfs module. 

_**Investigation ongoing**_  but I an considering a rollback/force install of 2.1 series ZFS until this is sorted.

**Workaround:**
Rebase to last version which has ZFS 2.1.13 which was tags `stable-20231012`  or `stable-zfs-20231012` depending on the image used.

Rebase examples:
```
# rpm-ostree rebase ostree-unverified-image:docker://ghcr.io/ublue-os/ucore:stable-zfs-20231012
# rpm-ostree rebase ostree-unverified-image:docker://ghcr.io/ublue-os/ucore-hci:stable-zfs-20231012
# rpm-ostree rebase ostree-unverified-image:docker://ghcr.io/ublue-os/fedora-coreos-zfs:stable-20231012
```

**Comment by bsherman** [comment]
We are now pinning ZFS to release 2.1.x ( see https://github.com/ublue-os/ucore-kmods/pull/8 ) as a workaround for this issue.

It's probably a good thing to do anyway... pinning to a known stable release series and not updating to the next one until at least 2.N.1 is released and proven.

Builds have been run on both `ucore-kmods` and `ucore` so the current release of both `:stable` and `:testing` images should both be back on 2.1.13 and working as expected.

**Comment by bsherman** [comment]
OK, turns out this 2.2.2 build is not ready either.

Here's the ko files packaged in 2.2.2:
```
$ rpm -ql kmod-zfs-6.5.11-300.fc39.x86_64-2.2.2-1.fc39.x86_64|grep ko$
/lib/modules/6.5.11-300.fc39.x86_64/extra/zfs/spl.ko
/lib/modules/6.5.11-300.fc39.x86_64/extra/zfs/zfs.ko
```

But on 2.1.14 we get:
```
$ rpm -ql kmod-zfs-6.5.11-300.fc39.x86_64-2.1.14-1.fc39.x86_64|grep ko$
/lib/modules/6.5.11-300.fc39.x86_64/extra/zfs/avl/zavl.ko
/lib/modules/6.5.11-300.fc39.x86_64/extra/zfs/icp/icp.ko
/lib/modules/6.5.11-300.fc39.x86_64/extra/zfs/lua/zlua.ko
/lib/modules/6.5.11-300.fc39.x86_64/extra/zfs/nvpair/znvpair.ko
/lib/modules/6.5.11-300.fc39.x86_64/extra/zfs/spl/spl.ko
/lib/modules/6.5.11-300.fc39.x86_64/extra/zfs/unicode/zunicode.ko
/lib/modules/6.5.11-300.fc39.x86_64/extra/zfs/zcommon/zcommon.ko
/lib/modules/6.5.11-300.fc39.x86_64/extra/zfs/zfs/zfs.ko
/lib/modules/6.5.11-300.fc39.x86_64/extra/zfs/zstd/zzstd.ko
```

This may need some real investigation at this point, since 2.1.x isn't supported on kernel 6.6, but we'll probably get that on CoreOS stable soon.

**Comment by ahjohannessen** [comment]
6.6.3 is on [testing](https://fedoraproject.org/coreos/release-notes?arch=x86_64&stream=testing) - so probably very soon in stable.

**Comment by vietchinh** [comment]
Perhaps this commit may explain the missing ko files and why the ko files are now in the root of zfs folder.
https://github.com/openzfs/zfs/commit/ad9e767657c3d3c0ec9e09a17f6732bcbf915401

``` 
linux: module: weld all but spl.ko into zfs.ko

Originally it was thought it would be useful to split up the kmods
by functionality.  This would allow external consumers to only load
what was needed.  However, in practice we've never had a case where
this functionality would be needed, and conversely managing multiple
kmods can be awkward.  Therefore, this change merges all but the
spl.ko kmod in to a single zfs.ko kmod.
```
If we open the pull request via the commit, in the first comment, it indicates that the missing modules are now aliased inside zfs.ko

https://github.com/openzfs/zfs/pull/13274#issuecomment-1086230046

> I also did a pass over licences and authors and now the modinfo looks like this:
> 
> ```
> root@kasan-test:~/zfs# modinfo module/zfs.ko  | head -30
> filename:       /root/zfs/module/zfs.ko
> version:        2.1.99-991_g5e98d1db2
> license:        CDDL
> license:        Dual BSD/GPL
> license:        zstd: Dual BSD/GPL
> license:        Lua: MIT
> author:         OpenZFS
> author:         zstd: Facebook, Inc.
> author:         Lua: Lua.org, PUC-Rio
> description:    ZFS
> alias:          zzstd
> alias:          zcommon
> alias:          zunicode
> alias:          znvpair
> alias:          zlua
> alias:          icp
> alias:          zavl
> alias:          devname:zfs
> alias:          char-major-10-249
> srcversion:     5C193FC283BE6EE531D4959
> depends:        spl
> retpoline:      Y
> name:           zfs
> vermagic:       5.16.0-5-amd64 SMP preempt mod_unload modversions
> ```
> 
> (Fletcher implementations are BSD/GPL.)
> 
> Only the first stanza matters, so this still taints the kernel.

I hope this helps a bit, even though it's more or less surface level, anything deeper is out of my field, unfortunately.

**Comment by bsherman** [comment]
@vietchinh very much appreciate your effort in digging around for relevant info!

If nothing else, this info has me giving things another try. 

For what it's worth, this is an issue others have seen on Fedora: https://discourse.practicalzfs.com/t/problem-with-rpm-kmod-builds-with-2-2-x/1148

I was hoping to find an answer there, but maybe we'll get to provide it.

**Comment by bsherman** [comment]
I've now confirmed that I can build ZFS 2.2 using the `ucore-kmods` scripts with only minor changes (use `dnf` instead of `rpm-ostree` etc) to support Fedora rather than Fedora CoreOS... 

I successfully built and loaded zfs 2.2.2 on kernel 6.6.6.

So, I'm re-testing the CoreOS builds.

**Comment by ahjohannessen** [comment]
Great news :)

**Comment by bsherman** [comment]
Oops, actually, #105 will close/fix this.
